# Generated by Django 4.0.1 on 2022-01-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='static/home/assets/images/team/style1/'),
        ),
    ]
