# Generated by Django 4.0.1 on 2022-01-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=150)),
                ('blog', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blogs/')),
                ('postedby', models.CharField(max_length=25)),
                ('createdat', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
